### ISSUE TITLE
Component DataTable not work

### ISSUE THREAD

**Issue by victorgt26** [efnegrete/tallerangular4#1]
When I try run the project:
ng serve
display the next Error:
```
ERROR in Error: DataTableModule is not an NgModule
    at _getNgModuleMetadata (/home/victorgt/CSIBOL/tallerangular4-master/tallerangular4/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/home/victorgt/CSIBOL/tallerangular4-master/tallerangular4/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/victorgt/CSIBOL/tallerangular4-master/tallerangular4/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
```

**Comment by victorgt26** [comment]
Logre Solucionarlo como indica en el repositorio:

Some times can be some problam with it. to fix it use import like this

import { DataTableModule } from 'angular-4-data-table/src/index';

add in .angular-cli.json

"scripts": [ "../node_modules/angular-4-data-table/dist/index.js" ],

and for prodaction build use
